/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    MainMenu: typeof import('./src/components/menu/MainMenu.vue')['default']
    Select3levelHeight: typeof import('./src/components/menu/components/Select3levelHeight.vue')['default']
    SetSize: typeof import('./src/components/menu/SetSize.vue')['default']
    Step1: typeof import('./src/components/menu/Step1.vue')['default']
    Step3: typeof import('./src/components/menu/Step3.vue')['default']
    Step4: typeof import('./src/components/menu/Step4.vue')['default']
    Step5: typeof import('./src/components/menu/Step5.vue')['default']
    StepDirect: typeof import('./src/components/menu/StepDirect.vue')['default']
    StepLeft: typeof import('./src/components/menu/StepLeft.vue')['default']
    StepRight: typeof import('./src/components/menu/StepRight.vue')['default']
    StepU: typeof import('./src/components/menu/StepU.vue')['default']
  }
}
